# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: semantics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='semantics.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fsemantics.proto\"\x1c\n\x0cSemanticType\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\tSemantics\x12\x1c\n\x05types\x18\x01 \x03(\x0b\x32\r.SemanticType')
)




_SEMANTICTYPE = _descriptor.Descriptor(
  name='SemanticType',
  full_name='SemanticType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SemanticType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=47,
)


_SEMANTICS = _descriptor.Descriptor(
  name='Semantics',
  full_name='Semantics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='types', full_name='Semantics.types', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=90,
)

_SEMANTICS.fields_by_name['types'].message_type = _SEMANTICTYPE
DESCRIPTOR.message_types_by_name['SemanticType'] = _SEMANTICTYPE
DESCRIPTOR.message_types_by_name['Semantics'] = _SEMANTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SemanticType = _reflection.GeneratedProtocolMessageType('SemanticType', (_message.Message,), dict(
  DESCRIPTOR = _SEMANTICTYPE,
  __module__ = 'semantics_pb2'
  # @@protoc_insertion_point(class_scope:SemanticType)
  ))
_sym_db.RegisterMessage(SemanticType)

Semantics = _reflection.GeneratedProtocolMessageType('Semantics', (_message.Message,), dict(
  DESCRIPTOR = _SEMANTICS,
  __module__ = 'semantics_pb2'
  # @@protoc_insertion_point(class_scope:Semantics)
  ))
_sym_db.RegisterMessage(Semantics)


# @@protoc_insertion_point(module_scope)
