# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ntest.proto\"1\n\x08TestEnum\"%\n\x01\x45\x12\t\n\x05\x46IRST\x10\x00\x12\n\n\x06SECOND\x10\x01\x12\t\n\x05THIRD\x10\x02\"W\n\x0bTestMessage\x12\x12\n\nteststring\x18\x01 \x01(\t\x12\x0f\n\x07testint\x18\x02 \x01(\x03\x12\x11\n\ttestfloat\x18\x03 \x01(\x02\x12\x10\n\x08testbool\x18\x04 \x01(\x08\"[\n\x0fTestComposition\x12\"\n\x0ctestmessages\x18\x01 \x03(\x0b\x32\x0c.TestMessage\x12$\n\x08testenum\x18\x02 \x01(\x0e\x32\x0b.TestEnum.E:\x05\x46IRST')
)



_TESTENUM_E = _descriptor.EnumDescriptor(
  name='E',
  full_name='TestEnum.E',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIRST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECOND', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THIRD', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=26,
  serialized_end=63,
)
_sym_db.RegisterEnumDescriptor(_TESTENUM_E)


_TESTENUM = _descriptor.Descriptor(
  name='TestEnum',
  full_name='TestEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TESTENUM_E,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=63,
)


_TESTMESSAGE = _descriptor.Descriptor(
  name='TestMessage',
  full_name='TestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='teststring', full_name='TestMessage.teststring', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='testint', full_name='TestMessage.testint', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='testfloat', full_name='TestMessage.testfloat', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='testbool', full_name='TestMessage.testbool', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=152,
)


_TESTCOMPOSITION = _descriptor.Descriptor(
  name='TestComposition',
  full_name='TestComposition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='testmessages', full_name='TestComposition.testmessages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='testenum', full_name='TestComposition.testenum', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=245,
)

_TESTENUM_E.containing_type = _TESTENUM
_TESTCOMPOSITION.fields_by_name['testmessages'].message_type = _TESTMESSAGE
_TESTCOMPOSITION.fields_by_name['testenum'].enum_type = _TESTENUM_E
DESCRIPTOR.message_types_by_name['TestEnum'] = _TESTENUM
DESCRIPTOR.message_types_by_name['TestMessage'] = _TESTMESSAGE
DESCRIPTOR.message_types_by_name['TestComposition'] = _TESTCOMPOSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestEnum = _reflection.GeneratedProtocolMessageType('TestEnum', (_message.Message,), dict(
  DESCRIPTOR = _TESTENUM,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:TestEnum)
  ))
_sym_db.RegisterMessage(TestEnum)

TestMessage = _reflection.GeneratedProtocolMessageType('TestMessage', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:TestMessage)
  ))
_sym_db.RegisterMessage(TestMessage)

TestComposition = _reflection.GeneratedProtocolMessageType('TestComposition', (_message.Message,), dict(
  DESCRIPTOR = _TESTCOMPOSITION,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:TestComposition)
  ))
_sym_db.RegisterMessage(TestComposition)


# @@protoc_insertion_point(module_scope)
